/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef IOSSETTINGS_AUTODEFS_H
#define IOSSETTINGS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSSETTINGS_NAME "iOSSettings"
#define S3E_EXT_IOSSETTINGS_HASH 0x4a3d6261

#endif /* !IOSSETTINGS_AUTODEFS_H */
