/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "iOSSettings.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       bool(*iOSSettingsGetBool_t)(const char* settingsname);
typedef       void(*iOSSettingsSetBool_t)(const char* settingsname, bool value);

/**
 * struct that gets filled in by iOSSettingsRegister
 */
typedef struct iOSSettingsFuncs
{
    iOSSettingsGetBool_t m_iOSSettingsGetBool;
    iOSSettingsSetBool_t m_iOSSettingsSetBool;
} iOSSettingsFuncs;

static iOSSettingsFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x4a3d6261, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: iOSSettings");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x4a3d6261, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool iOSSettingsAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

bool iOSSettingsGetBool(const char* settingsname)
{
    IwTrace(IOSSETTINGS_VERBOSE, ("calling iOSSettings[0] func: iOSSettingsGetBool"));

    if (!_extLoad())
        return false;

    return g_Ext.m_iOSSettingsGetBool(settingsname);
}

void iOSSettingsSetBool(const char* settingsname, bool value)
{
    IwTrace(IOSSETTINGS_VERBOSE, ("calling iOSSettings[1] func: iOSSettingsSetBool"));

    if (!_extLoad())
        return;

    g_Ext.m_iOSSettingsSetBool(settingsname, value);
}
