/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "iOSSettings_autodefs.h"
#include "s3eEdk.h"
#include "iOSSettings.h"
//Declarations of Init and Term functions
extern s3eResult iOSSettingsInit();
extern void iOSSettingsTerminate();


void iOSSettingsRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)iOSSettingsGetBool;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("iOSSettings", funcPtrs, sizeof(funcPtrs), flags, iOSSettingsInit, iOSSettingsTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int iOSSettingsStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&iOSSettingsRegisterExt;
    return 0;
}

int g_iOSSettingsVal = iOSSettingsStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    iOSSettingsRegisterExt();
}
#endif

#endif
